/**
 * Photo Wall — Grandma's Wall of Bananas.
 *
 * A maximalist "salon hang": a curated random subset of photos hung in real
 * frames, packed to fill the wall. Frames come in two switchable themes
 * (mid-century wood / ornamental brass). "Rehang" reshuffles the selection,
 * sizes, and tilt.
 *
 * Layout is a true aspect-ratio masonry: each frame keeps its photo's real
 * proportions (no cropping). We give every frame a random column span, then
 * measure its natural height and set a matching grid row-span so the grid
 * packs tightly (grid-auto-flow: dense). Dimensions come from manifest.json
 * (generated by underScore's knowledge/tools/process-images.py).
 */

const POOL_DIR = '/assets/photowall';
const MANIFEST = `${POOL_DIR}/manifest.json`;
const WALL_SIZE = 24; // photos per hang
const ROW_UNIT = 5; // px — grid-auto-rows; small = fine-grained packing
const GAP = 8; // px — must match CSS gap (tight salon hang)

// Selectable photobooth-prop cursors (SVGs in /assets/icons/cursors/). hx/hy =
// hotspot in the SVG's own pixel size.
const CURSOR_DIR = '/assets/icons/cursors';
const CURSOR_KEY = 'photowall-cursor';
const CURSOR_PROPS: ReadonlyArray<{ id: string; label: string; hx: number; hy: number }> = [
    { id: 'granny-glasses', label: 'Granny glasses', hx: 24, hy: 16 },
    { id: 'lennon-glasses', label: 'Round glasses', hx: 22, hy: 15 },
    { id: 'cateye-glasses', label: 'Cat-eye glasses', hx: 27, hy: 13 },
    { id: 'star-glasses', label: 'Star glasses', hx: 27, hy: 12 },
    { id: 'mustache', label: 'Mustache', hx: 26, hy: 12 },
    { id: 'lips', label: 'Lips', hx: 22, hy: 13 },
    { id: 'tophat', label: 'Top hat', hx: 20, hy: 29 },
    { id: 'cowboyhat', label: 'Cowboy hat', hx: 24, hy: 18 },
    { id: 'partyhat', label: 'Party hat', hx: 17, hy: 24 },
    { id: 'monocle', label: 'Monocle', hx: 18, hy: 16 },
];

interface Photo {
    file: string;
    w: number;
    h: number;
}

let pool: Photo[] = [];
let current: Photo[] = [];

async function loadPool(): Promise<Photo[]> {
    try {
        const res = await fetch(MANIFEST, { cache: 'no-store' });
        if (!res.ok) return [];
        const data: unknown = await res.json();
        if (!Array.isArray(data)) return [];
        // Tolerate the legacy string[] manifest as well as the {file,w,h} form.
        return data
            .map((e): Photo | null => {
                if (typeof e === 'string') return { file: e, w: 3, h: 2 };
                if (e && typeof e === 'object' && 'file' in e) {
                    const o = e as Record<string, unknown>;
                    return {
                        file: String(o.file),
                        w: Number(o.w) || 3,
                        h: Number(o.h) || 2,
                    };
                }
                return null;
            })
            .filter((p): p is Photo => p !== null);
    } catch {
        return [];
    }
}

/** Fisher–Yates shuffle, then take n. */
function sample<T>(arr: T[], n: number): T[] {
    const a = [...arr];
    for (let i = a.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [a[i], a[j]] = [a[j], a[i]];
    }
    return a.slice(0, Math.min(n, a.length));
}

/** Column count scaled to the wall width (~150px per base column). */
function columnCount(wall: HTMLElement): number {
    const width = wall.clientWidth || 1000;
    return Math.min(12, Math.max(2, Math.round(width / 150)));
}

/** Random column span for a frame, biased by orientation, scaled to grid width.
 *  Wide spread (xs → hero) for size variety across the wall. */
function colSpan(photo: Photo, cols: number): number {
    const xs = Math.max(1, Math.round(cols / 7));
    const small = Math.max(1, Math.round(cols / 5));
    const med = Math.max(2, Math.round(cols / 3.5));
    const large = Math.max(3, Math.round(cols / 2.4));
    const portrait = photo.w < photo.h;
    const r = Math.random();
    let span = r < 0.18 ? xs : r < 0.5 ? small : r < 0.82 ? med : large;
    if (portrait && Math.random() < 0.45) span = Math.min(span, small); // portraits read narrower
    if (!portrait && r > 0.9) span = large; // a few hero landscapes
    return Math.min(cols, Math.max(1, span));
}

/** Most frames are rectangular (true aspect, no crop); a sprinkle are round or
 *  oval cameos (square/portrait crop) for variety. */
function shapeFor(): string {
    const r = Math.random();
    if (r < 0.12) return 'shape-round';
    if (r < 0.22) return 'shape-oval';
    return 'shape-rect';
}

function buildFrame(photo: Photo): HTMLElement {
    const fig = document.createElement('figure');
    fig.className = `frame ${shapeFor()}`;
    fig.style.setProperty('--tilt', `${(Math.random() * 1.8 - 0.9).toFixed(2)}deg`);

    const img = document.createElement('img');
    img.src = `${POOL_DIR}/${photo.file}`;
    img.alt = "A framed photo from Yiayia's Wall of Bananas";
    img.loading = 'lazy';
    img.width = photo.w;
    img.height = photo.h;
    fig.appendChild(img);
    return fig;
}

/** After frames have a width (col span applied), measure natural heights and
 *  set matching row spans so the masonry packs. Batched read-then-write. */
function applyRowSpans(wall: HTMLElement): void {
    const frames = Array.from(wall.children) as HTMLElement[];
    const heights = frames.map((f) => f.getBoundingClientRect().height); // read phase
    frames.forEach((f, i) => {
        const span = Math.max(1, Math.round((heights[i] + GAP) / (ROW_UNIT + GAP)));
        f.style.gridRowEnd = `span ${span}`; // write phase
    });
}

function renderWall(wall: HTMLElement): void {
    const cols = columnCount(wall);
    wall.style.gridTemplateColumns = `repeat(${cols}, 1fr)`;
    wall.replaceChildren();
    current.forEach((photo, i) => {
        const frame = buildFrame(photo);
        frame.style.gridColumnEnd = `span ${colSpan(photo, cols)}`;
        frame.dataset.index = String(i); // for the lightbox
        wall.appendChild(frame);
    });
    // Let layout settle (widths resolved) before measuring heights.
    requestAnimationFrame(() => applyRowSpans(wall));
}

/** Fullscreen lightbox: click a photo to enlarge; arrows / swipe through the
 *  current hang; Esc, ✕, or backdrop click to return to the wall. */
function setupLightbox(wall: HTMLElement): void {
    const lb = document.getElementById('photowall-lightbox');
    const lbImg = lb?.querySelector('.pw-lb-img') as HTMLImageElement | null;
    if (!lb || !lbImg) return;

    let index = -1;
    const isOpen = (): boolean => !lb.hidden;

    const showAt = (i: number): void => {
        if (current.length === 0) return;
        index = (i + current.length) % current.length; // wrap
        lbImg.src = `${POOL_DIR}/${current[index].file}`;
        lb.hidden = false;
        document.body.classList.add('pw-lb-open');
    };
    const close = (): void => {
        lb.hidden = true;
        document.body.classList.remove('pw-lb-open');
        index = -1;
    };

    // Open from a clicked frame (event delegation).
    wall.addEventListener('click', (e) => {
        const fig = (e.target as HTMLElement).closest('.frame') as HTMLElement | null;
        if (!fig) return;
        const i = Number(fig.dataset.index);
        if (!Number.isNaN(i)) showAt(i);
    });

    // Controls + backdrop.
    lb.addEventListener('click', (e) => {
        const action = (e.target as HTMLElement).dataset.action;
        if (action === 'prev') showAt(index - 1);
        else if (action === 'next') showAt(index + 1);
        else if (action === 'close' || e.target === lb) close();
    });

    // Keyboard.
    document.addEventListener('keydown', (e) => {
        if (!isOpen()) return;
        if (e.key === 'Escape') close();
        else if (e.key === 'ArrowLeft') showAt(index - 1);
        else if (e.key === 'ArrowRight') showAt(index + 1);
    });
}

/** Build the prop-cursor picker; clicking a prop sets the cursor used over the
 *  photos and the enlarged view (a CSS var on <body>) and remembers the choice. */
function setupCursorPicker(): void {
    const picker = document.getElementById('photowall-cursor-picker');
    if (!picker) return;

    const apply = (id: string): void => {
        const prop = CURSOR_PROPS.find((p) => p.id === id) ?? CURSOR_PROPS[0];
        // On <body> so both the wall frames and the lightbox image inherit it.
        document.body.style.setProperty('--frame-cursor', `url('${CURSOR_DIR}/${prop.id}.svg') ${prop.hx} ${prop.hy}`);
        picker.querySelectorAll('.pw-prop').forEach((b) =>
            b.classList.toggle('is-active', (b as HTMLElement).dataset.id === prop.id),
        );
        try {
            localStorage.setItem(CURSOR_KEY, prop.id);
        } catch {
            /* private mode / storage disabled — fine, just don't persist */
        }
    };

    picker.replaceChildren();
    for (const prop of CURSOR_PROPS) {
        const btn = document.createElement('button');
        btn.type = 'button';
        btn.className = 'pw-prop';
        btn.dataset.id = prop.id;
        btn.title = prop.label;
        btn.setAttribute('aria-label', `Cursor: ${prop.label}`);
        const img = document.createElement('img');
        img.src = `${CURSOR_DIR}/${prop.id}.svg`;
        img.alt = prop.label;
        btn.appendChild(img);
        btn.addEventListener('click', () => apply(prop.id));
        picker.appendChild(btn);
    }

    let saved = CURSOR_PROPS[0].id;
    try {
        saved = localStorage.getItem(CURSOR_KEY) ?? saved;
    } catch {
        /* ignore */
    }
    apply(saved);
}

export async function initializePhotowall(): Promise<void> {
    const wall = document.getElementById('photowall-wall');
    const rehang = document.getElementById('photowall-rehang');
    const toggle = document.getElementById('photowall-frame-toggle');
    const empty = document.getElementById('photowall-empty');
    if (!wall) return;

    pool = await loadPool();
    if (pool.length === 0) {
        if (empty) empty.hidden = false;
        if (rehang) rehang.hidden = true;
        if (toggle) toggle.hidden = true;
        return;
    }

    const hang = (): void => {
        current = sample(pool, WALL_SIZE);
        renderWall(wall);
    };
    hang();
    setupLightbox(wall);
    setupCursorPicker();

    rehang?.addEventListener('click', hang);

    let brass = false;
    toggle?.addEventListener('click', () => {
        brass = !brass;
        wall.classList.toggle('theme-brass', brass);
        wall.classList.toggle('theme-wood', !brass);
        toggle.textContent = brass ? '🖼 Frames: Brass' : '🪵 Frames: Wood';
        // Frame padding differs by theme → heights change → re-measure spans.
        requestAnimationFrame(() => applyRowSpans(wall));
    });

    // Recompute on resize (column count + heights change). Debounced.
    let resizeTimer = 0;
    window.addEventListener('resize', () => {
        window.clearTimeout(resizeTimer);
        resizeTimer = window.setTimeout(() => renderWall(wall), 150);
    });
}
